### ISSUE TITLE
Novo cálculo para taxa do Tesouro Selic

### ISSUE THREAD

**Issue by naoliv** [marcelorodrigo/rendafixa#44]
A partir de 1 de agosto o cálculo da taxa será alterado (com isenção para aplicações de até R$10 mil)

https://g1.globo.com/economia/noticia/2020/07/23/tesouro-direto-aplicacao-ate-r-10-mil-em-titulos-corrigidos-pela-selic-tem-taxa-de-custodia-zerada.ghtml
https://economia.uol.com.br/financas-pessoais/noticias/redacao/2020/07/24/tesouro-selic-ganha-folego-com-taxa-zerada.htm

**Comment by naoliv** [comment]
Marcelo, acho que o cálculo aqui vai ser mais complexo:
https://github.com/marcelorodrigo/rendafixa/blob/49ec8173e87e0615dcc777051f429562b7dfd5b1/public/js/calculadora.js#L63-L69
https://github.com/marcelorodrigo/rendafixa/blob/49ec8173e87e0615dcc777051f429562b7dfd5b1/public/js/calculadora.js#L89

O que deveria acontecer é:
* valor até 10 mil, isenção
* valor acima de 10 mil, cobra taxa (mas apenas para o que passar os 10 mil)

Se eu entendi direito o código, se a pessoa investir R$10001, o programa calculará taxa em cima desse valor total (enquanto deveria pagar taxa apenas em cima do R$1 que passou os 10 mil isentos)

**Comment by marcelorodrigo** [comment]
Verdade @naoliv 
Ao menos o que a [B3](http://www.b3.com.br/pt_br/noticias/tesouro-selic.htm
) menciona, é exatamente o que você comentou

Reabri a issue para um novo PR 👍 
Obrigado!

**Comment by marcelorodrigo** [comment]
Obrigado @naoliv [;-)]

**Comment by naoliv** [comment]
Eu que agredeço!
